version: '3.8'
services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - '8000:8000'
    depends_on:
      - frontend
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'